In [ ]:
import numpy as np
list=[2, 3.5, 'india', -34]

type(list)

arr=np.array(list)
print(arr)

['2' '3.5' 'india' '-34']


In [ ]:
type(arr)

numpy.ndarray

In [ ]:
import numpy as np
my_list1=[4,5,6,7,8]
my_list2=[-2,6,8,3,4]
my_list3=[5,6,0,-3,5]

arr=np.array([my_list1, my_list2, my_list3])
print(arr)

[[ 4  5  6  7  8]
 [-2  6  8  3  4]
 [ 5  6  0 -3  5]]


In [ ]:
arr[0:2,2:]

array([[6, 7, 8],
       [8, 3, 4]])

In [ ]:
arr[0:2,0:2]

array([[ 4,  5],
       [-2,  6]])

In [ ]:
arr[1:,:4]

array([[-2,  6,  8,  3],
       [ 5,  6,  0, -3]])

In [ ]:
np.linspace(1,10)

array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
        1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122,
        2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
        3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592,
        4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
        5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061,
        6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
        7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531,
        8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
        9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ])

In [ ]:
np.random.rand(5,6)#here 3 & 4 are indicating rows & column // it has a default range of 0-1(i being exclusive in nature)

array([[0.91424273, 0.6086574 , 0.31436393, 0.98527604, 0.70891568,
        0.32207448],
       [0.3297023 , 0.64331407, 0.37750576, 0.19589115, 0.1073368 ,
        0.40456162],
       [0.93554838, 0.60887741, 0.87656125, 0.00442685, 0.42997048,
        0.75307132],
       [0.28726509, 0.63884696, 0.11266644, 0.45945007, 0.85878972,
        0.43654471],
       [0.54933091, 0.86612955, 0.62896915, 0.00487701, 0.13082403,
        0.19248956]])

In [ ]:
np.random.randint(100,200,20)

array([169, 147, 190, 175, 121, 135, 190, 114, 173, 178, 117, 105, 114,
       199, 116, 144, 180, 103, 178, 117])